# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Botanic Garden Online
email: info@davideprati.com
math: your-email@domain.com
description_header: This is the first online botanic garden.
description: > # this means to ignore newlines until "baseurl:"
  The online Botanic Garden is always opened
description_metatag: > # this means to ignore newlines until "baseurl:"
  The online Botanic Garden is a garden full of trees, flowers and leaves 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://botanicgarden.online" # the base hostname & protocol for your site
twitter_username: edapx
github_username:  edap
exclude: ['*/node_modules']
collections:
  projects:
    cover: ""
    cover_vimeo: ""
    output: true
# Build settings
markdown: kramdown
